### PR TITLE
feat: add task completion survey banner

### PR DESCRIPTION
**Pull request by zebateira**
This is the first implementation of the Task Completion Survey banner (package [here](https://github.com/protocol/task-completion-survey-banner))
Let's discuss any changes you might want here.

Current behavior:

- When the user clicks on the close button or the form link CTA, the form will disappear for 30 days (number of days customizable per instance, aka, per website).
    - Let me know if you want me to change it so that when click on the CTA the form will not disappear.
- Data is saved as local storage under the key `pl:task-completion-survey-banner:state`.
    - If you want to test closing it and open again you have to open the site in another browser profile/incognito or another browser. An even easier solution is to clean the application data of the website on the browser, or open the dev tools and on the application tab, select the local storage section and delete the item `pl:task-completion-survey-banner:state` by selecting with the mouse and deleting with the backspace key.
- Banner is currently only being displayed in the homepage. Should it be showing on all the other pages?
- I published the package under my npm user, but I'll try to publish it under the most appropriate org soon. This is not a blocker though.

I don't feel like the UI styles are quite ready, so would appreciate some feedback from @jessicaschilling on this!

image

### CODE REVIEW

**Review by jessicaschilling — COMMENTED** [review]
@zebateira - this is awesome 😊 
My only suggestion might be to add a few px of border-radius to the button and change the hover state to something a little less flashy: just a darken or brighten effect would work. Just in thinking of how we might get a little closer to consistency with the many sites in which we'll be adding this ...

**Comment by zebateira** [comment]
@jessicaschilling thank you for taking a look! 🙏 
fixed to match the ipfs website:

https://user-images.githubusercontent.com/2353186/127470156-9d9903ef-9419-4ca2-9858-0adfcda02132.mp4

**Comment by atopal** [comment]
Thank you Ze! This is great! Start page only is fine, if we have another one for the docs. In the docs the placement should probably be an overlay in the top right corner where people are less likely to click it away.

**Review by atopal — APPROVED** [review]
LGTM!

**Comment by zebateira** [comment]
@atopal is the typeform url ok?

**Review by jessicaschilling — APPROVED** [review]
Thanks!

**Comment by zebateira** [comment]
> In the docs the placement should probably be an overlay in the top right corner where people are less likely to click it away.

Going to PR the docs soon, and we can talk about that there 👍

**Comment by cwaring** [comment]
Closing as stale, may revisit later.

**Pull request closed without merging**
